#!/usr/bin/env python3
css_word_voice = 'div.word-info > div.pronounces > span.word-audio'
css_word_text  = 'div.word-info > div.word-text > h2'
css_word_prnounces  = 'div.word-info > div.pronounces'
css_word_prnounces_kata = 'span'
css_word_info='div.simple'
word_text=[]
word_info=[]
word_voice=[]
word_prnounces=[]
v=1
import lxml.html

f = open('kodomo.html')
tree = lxml.html.fromstring(f.read())

for voice in tree.cssselect(css_word_voice):
    word_voice.append(str(voice.attrib['data-src']))


for word_text_temp in tree.cssselect(css_word_text):
    word_text.append(word_text_temp.text_content())

for word_info_temp in tree.cssselect(css_word_info):
    word_info.append(word_info_temp.text_content().split())

i=0
for voice in tree.cssselect(css_word_prnounces):
    if v==0:
        word_prnounces.append(word_text[i]+'|假名:'+voice.cssselect(css_word_prnounces_kata)[0].text_content()+'|罗马音:'+voice.cssselect(css_word_prnounces_kata)[1].text_content())
    elif v==1:
        word_prnounces.append(word_text[i]+'|假名:'+voice.cssselect(css_word_prnounces_kata)[0].text_content()+'|罗马音:'+voice.cssselect(css_word_prnounces_kata)[1].text_content()+'\n音频链接: '+word_voice[i])
    i+=1


i=0
for word_info_temp in tree.cssselect(css_word_info):
    print(word_prnounces[i])
    i+=1
    for sub_word_info in word_info_temp.text_content().split():
        print(sub_word_info)


print(word_prnounces)
