#!/bin/bash

set -x

CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null)

if [ -n "$CURRENT_TAG" ]; then
  PREV_TAG=$(git describe --tags --abbrev=0 --exclude="$CURRENT_TAG" 2>/dev/null)
fi

if [ -z "$CURRENT_TAG" ]; then
  git log --oneline
else
  git log $(git describe --tags --abbrev=0 --exclude=$(git describe --tags))..$(git describe --tags) --oneline
fi
