[package]
name = "hj-rust"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["native", "common", "dict", "worker", "web"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
frankenstein = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }

aws_lambda_events = "0"
lambda_runtime = "0"

hjnative = { path = "./native" }
hjcommon = { path = "./common" }
hjdict = { path = "./dict" }


[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
frankenstein = { version = "0.44", features = ["client-reqwest"] }
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
env_logger = "0.11"
cloudflare = { version = "0.14", default-features = false, features = [
    "rustls-tls",
] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
panic = 'abort'   # Abort on panic
strip = true      # Strip symbols from binary*
