[package]
name = "hj-rust"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["native", "common", "dict", "worker", "web"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
frankenstein = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }

aws_lambda_events = "1"
lambda_runtime = "1"

hjnative = { path = "./native" }
hjcommon = { path = "./common" }
hjdict = { path = "./dict" }


[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "^0.4"
base64 = "^0.22"
reqwest = { version = "^0.13", default-features = false, features = [
    "rustls",
    "json",
    "query",
] }
frankenstein = { version = "^0.45", features = ["client-reqwest"] }
tokio = { version = "1", default-features = false, features = ["macros", "rt"] }
env_logger = "0.11"
cloudflare = { version = "^0.14", default-features = false, features = [
    "rustls-tls",
] }
scraper = "^0.25"
ego-tree = "^0.10"
html2text = { version = "^0.16", default-features = false }
dom_smoothie = { version = "^0.14", features = ["aho-corasick"] }
rust-embed = "^8.7"
worker = { version = "^0.7", features = ["d1"] }
worker-macros = "^0.7"
console_error_panic_hook = "^0.1"
wasm-bindgen = "^0.2"
web-sys = { version = "^0.3", features = ["console"] }
url = "2.5.8"
jsonwebtoken = "9"
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
panic = 'abort'   # Abort on panic
strip = true      # Strip symbols from binary*
