name = "dictdeck"
main = "worker/build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "worker-build --release"
cwd = "worker"

[vars]
TELEGRAM_TOKEN = ""
ALLOW_USERS = ""
MAINTAINER_ID = ""          # send random word to the chat id when cron job run
AUTH_USERNAME = ""
AUTH_PASSWORD = ""
AUTH_SECRET = "test"
AUTH_TOKEN_EXPIRATION = "1" # in days

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"

[triggers]
crons = ["*/20 0-15 * * *"] # UTC timezone

[placement]
mode = "smart"

[assets]
directory = "./web/out"
binding = "ASSETS"

[env.dev]

[env.dev.vars]
TELEGRAM_TOKEN = ""
ALLOW_USERS = ""
MAINTAINER_ID = ""          # send random word to the chat id when cron job run
AUTH_USERNAME = "admin"
AUTH_PASSWORD = "password"
AUTH_SECRET = "test"
AUTH_TOKEN_EXPIRATION = "1" # in days
[env.dev.ai]
binding = "AI"
[[env.dev.d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"

[env.production]
name = "dictdeck"
[env.production.ai]
binding = "AI"
[env.production.observability.logs]
enabled = true
[env.production.observability.traces]
enabled = true
[env.production.triggers]
crons = ["*/20 0-15 * * *"]
[[env.production.d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"


[env.ci]
name = "dictdeck"
[env.ci.ai]
binding = "AI"
[env.ci.observability.logs]
enabled = true
[env.ci.observability.traces]
enabled = true
[env.ci.triggers]
crons = ["*/20 0-15 * * *"]
[env.ci.build]
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
. $HOME/.cargo/env && \
rustup target add wasm32-unknown-unknown && \
npm install --prefix web && \
npm run build --prefix web && \
cargo install -q worker-build && \
cd worker && worker-build --release"""
[[env.ci.d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"
