name = "hj-rust"
main = "worker/build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "worker-build --release"
cwd = "worker"

[vars]
TELEGRAM_TOKEN = ""
ALLOW_USERS = ""
MAINTAINER_ID = ""          # send random word to the chat id when cron job run
AUTH_USERNAME = ""
AUTH_PASSWORD = ""
AUTH_TOKEN_EXPIRATION = "1" # in days

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"

[triggers]
crons = ["*/20 0-15 * * *"] # UTC timezone

[placement]
mode = "smart"

[assets]
directory = "./web/out"
binding = "ASSETS"

[env.dev]
[env.dev.build]
command = "worker-build --release"
cwd = "worker"

[env.dev.vars]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"

[env.production]
[env.production.build]
command = """
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
. $HOME/.cargo/env && \
rustup target add wasm32-unknown-unknown && \
npm install --prefix web && \
npm run build --prefix web && \
cargo install -q worker-build && \
cd worker && worker-build --release"""

[env.production.vars]

[[env.production.d1_databases]]
binding = "DB"
database_name = "words"
database_id = "e157547e-8649-496c-8abb-bd3c07835cf6"
