name = "${WORKER_NAME}"
main = "worker/build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "worker-build --release"
cwd = "worker"

[vars]
TELEGRAM_TOKEN = "${TELEGRAM_TOKEN}"
ALLOW_USERS = "${ALLOW_USERS}"
MAINTAINER_ID = "${MAINTAINER_ID}"          # send random word to the chat id when cron job run
CUSTOM_LLM_JSON_CONFIG="${CUSTOM_LLM_JSON_CONFIG}"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "${D1_DATABASE_NAME}"
database_id = "${D1_DATABASE_ID}"

[triggers]
crons = ["${SCHEDULE}"] # UTC timezone

[placement]
mode = "smart"

[assets]
directory = "./web/out"
binding = "ASSETS"
