[package]
name = "hjnative"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
frankenstein = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
cloudflare = { workspace = true }

value2struct = { path = "../value2struct" }
hjcommon = { path = "../common" }
hjdict = { path = "../dict" }
d1-orm = "0.1.2"
async-trait = "0.1.89"
hj_ai = { path = "../ai" }
futures = "0.3.32"
