[package]
name = "hjcommon"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
log = { workspace = true }
frankenstein = { workspace = true }
rust-embed = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
async-trait = "0.1"
subtle = "2"

value2struct = { path = "../value2struct" }
hjdict = { path = "../dict" }
tg-bot-worker = { path = "../tg-bot-worker" }

# test only
tokio = { workspace = true }
env_logger = { workspace = true }
