[package]
name = "hjcommon"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
log = { workspace = true }
frankenstein = { workspace = true }
rust-embed = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }
subtle = "2"

value2struct = { path = "../value2struct" }
hjdict = { path = "../dict" }

# test only
tokio = { workspace = true }
env_logger = { workspace = true }
d1-orm = "0.1.1"
