[package]
name = "hjworker"
version = "0.1.0"
edition = "2024"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
frankenstein = { workspace = true }
log = { workspace = true }
cloudflare = { workspace = true }
worker = { workspace = true }
worker-macros = { workspace = true }
console_error_panic_hook = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
jsonwebtoken = { workspace = true }
chrono = { workspace = true }

hjcommon = { path = "../common" }
