[package]
name = "hjworker"
version = "0.1.0"
edition = "2024"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
reqwest = { workspace = true }
serde = { workspace = true }
frankenstein = { workspace = true }
log = { workspace = true }

worker = { version = "0.6", features = ["d1"] }
worker-macros = "0.6"
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2.100"
cloudflare = "0.14"
console_log = "1.0"

hjcommon = { path = "../common" }
