name: Go

on:
  push:
    branches: [ golang ]
  pull_request:
    branches: [ golang ]

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: [mips, mips64, 386, arm, arm64, amd64]
        os: [linux, android, darwin, freebsd, openbsd, windows]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Build hj
      run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w -buildid=" -trimpath -v -o output/hj_${{ matrix.os }}_${{ matrix.arch }} ./cmd/hj/...

    - name: Build google
      run: CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags="-s -w -buildid=" -trimpath -v -o output/google_${{ matrix.os }}_${{ matrix.arch }} ./cmd/google/...

    - name: upload_${{ matrix.os }}_${{ matrix.arch }}
      uses: actions/upload-artifact@v3
      with:
        name: "${{ matrix.os }}_${{ matrix.arch }}"
        path: |
          ./output/hj_${{ matrix.os }}_${{ matrix.arch }}
          ./output/google_${{ matrix.os }}_${{ matrix.arch }}
