name: Go

on:
  push:
    branches: [ golang ]
  pull_request:
    branches: [ golang ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go vet ./...

    - name: Build-ALL
      run: bash build.sh

    - name: upload_linux
      uses: actions/upload-artifact@v3
      with:
        name: "linux"
        path: ./output/linux

    - name: upload_android
      uses: actions/upload-artifact@v3
      with:
        name: "android"
        path: ./output/android
  
    - name: upload_darwin
      uses: actions/upload-artifact@v3
      with:
        name: "darwin"
        path: ./output/darwin

    - name: upload_freebsd
      uses: actions/upload-artifact@v3
      with:
        name: "freebsd"
        path: ./output/freebsd

    - name: upload_openbsd
      uses: actions/upload-artifact@v3
      with:
        name: "openbsd"
        path: ./output/openbsd

    - name: upload_windows
      uses: actions/upload-artifact@v3
      with:
        name: "windows"
        path: ./output/windows
